#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Embed a binary blob as a 16-byte-aligned C array."""
import sys


def main():
    blob_path, inc_path = sys.argv[1], sys.argv[2]
    with open(blob_path, "rb") as f:
        data = f.read()
    with open(inc_path, "w") as f:
        f.write("/* Generated by blob2inc.py - do not edit */\n")
        f.write("static const uint8_t model_blob[%d] __aligned(16) = {\n"
                % len(data))
        for i in range(0, len(data), 12):
            f.write("\t" + " ".join("0x%02x," % b for b in data[i:i + 12])
                    + "\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
