/* SPDX-License-Identifier: Apache-2.0 */
/*
 * GENERATED by tools/syn_flash_layout.py - do not edit; edit the tool and regenerate.
 *
 * SynapticOS on-chip flash partition map (FRDM-MCXN947, dual-core).
 * All addresses are plain (non-secure); CPU0 memory-mapped reads
 * must go through the secure alias (SYN_FLASH_XIP_ADDR).
 *
 * Safety invariants enforced below:
 *  - bank 0 (CPU0 XIP) contains no OTA-writable partition
 *  - nothing OTA-writable intersects the CPU1 image reserve
 *  - every boundary is aligned to the 8 KB erase sector
 */
#ifndef SYNAPTIC_SYN_FLASH_MAP_H_
#define SYNAPTIC_SYN_FLASH_MAP_H_

#include <zephyr/toolchain.h>
#include <zephyr/devicetree.h>

#define SYN_FLASH_TOTAL_SIZE   0x00200000UL
#define SYN_FLASH_BANK_SIZE    0x00100000UL
#define SYN_FLASH_BANK1_BASE   0x00100000UL
#define SYN_FLASH_SECTOR_SIZE  0x2000UL
#define SYN_FLASH_PAGE_SIZE    128UL
#define SYN_FLASH_SECURE_ALIAS 0x10000000UL

/* CPU0 (secure) sees flash at the alias; CPU1 at plain addresses. */
#ifdef CONFIG_SOC_MCXN947_CPU1
#define SYN_FLASH_XIP_ADDR(off) ((uintptr_t)(off))
#else
#define SYN_FLASH_XIP_ADDR(off) ((uintptr_t)(SYN_FLASH_SECURE_ALIAS + (off)))
#endif

#define SYN_PART_CPU0_FW_OFFSET 0x00000000UL
#define SYN_PART_CPU0_FW_SIZE   0x00100000UL
#define SYN_PART_CPU1_IMG_OFFSET 0x00100000UL
#define SYN_PART_CPU1_IMG_SIZE   0x00020000UL
#define SYN_PART_REGISTRY_A_OFFSET 0x00120000UL
#define SYN_PART_REGISTRY_A_SIZE   0x00002000UL
#define SYN_PART_REGISTRY_B_OFFSET 0x00122000UL
#define SYN_PART_REGISTRY_B_SIZE   0x00002000UL
#define SYN_PART_SLOT_A_OFFSET 0x00124000UL
#define SYN_PART_SLOT_A_SIZE   0x0006E000UL
#define SYN_PART_SLOT_B_OFFSET 0x00192000UL
#define SYN_PART_SLOT_B_SIZE   0x0006E000UL

/* OTA-writable window: nothing outside it may ever be erased or
 * programmed at runtime. The flash port layer enforces this at
 * runtime as well (last line of defence).
 */
#define SYN_FLASH_WRITABLE_BASE 0x00120000UL
#define SYN_FLASH_WRITABLE_END  0x00200000UL

/* Layout invariants (compile-time) */
BUILD_ASSERT(SYN_PART_CPU0_FW_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "CPU0_FW offset not sector-aligned");
BUILD_ASSERT(SYN_PART_CPU0_FW_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "CPU0_FW size not sector-aligned");
BUILD_ASSERT(SYN_PART_CPU0_FW_OFFSET == 0x00000000UL,
	     "CPU0_FW not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_CPU1_IMG_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "CPU1_IMG offset not sector-aligned");
BUILD_ASSERT(SYN_PART_CPU1_IMG_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "CPU1_IMG size not sector-aligned");
BUILD_ASSERT(SYN_PART_CPU1_IMG_OFFSET == 0x00100000UL,
	     "CPU1_IMG not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_REGISTRY_A_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "REGISTRY_A offset not sector-aligned");
BUILD_ASSERT(SYN_PART_REGISTRY_A_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "REGISTRY_A size not sector-aligned");
BUILD_ASSERT(SYN_PART_REGISTRY_A_OFFSET == 0x00120000UL,
	     "REGISTRY_A not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_REGISTRY_B_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "REGISTRY_B offset not sector-aligned");
BUILD_ASSERT(SYN_PART_REGISTRY_B_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "REGISTRY_B size not sector-aligned");
BUILD_ASSERT(SYN_PART_REGISTRY_B_OFFSET == 0x00122000UL,
	     "REGISTRY_B not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_SLOT_A_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "SLOT_A offset not sector-aligned");
BUILD_ASSERT(SYN_PART_SLOT_A_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "SLOT_A size not sector-aligned");
BUILD_ASSERT(SYN_PART_SLOT_A_OFFSET == 0x00124000UL,
	     "SLOT_A not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_SLOT_B_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "SLOT_B offset not sector-aligned");
BUILD_ASSERT(SYN_PART_SLOT_B_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL,
	     "SLOT_B size not sector-aligned");
BUILD_ASSERT(SYN_PART_SLOT_B_OFFSET == 0x00192000UL,
	     "SLOT_B not contiguous with previous partition");
BUILD_ASSERT(SYN_PART_SLOT_B_OFFSET + SYN_PART_SLOT_B_SIZE == SYN_FLASH_TOTAL_SIZE,
	     "map does not cover the full flash");
BUILD_ASSERT(SYN_PART_CPU1_IMG_OFFSET == SYN_FLASH_BANK1_BASE,
	     "CPU1 image must sit at bank 1 base (SYSCON CPBOOT target)");
BUILD_ASSERT(SYN_FLASH_WRITABLE_BASE >= SYN_PART_CPU1_IMG_OFFSET + SYN_PART_CPU1_IMG_SIZE,
	     "OTA-writable window intersects the CPU1 image reserve");
BUILD_ASSERT(SYN_FLASH_WRITABLE_END <= SYN_FLASH_TOTAL_SIZE,
	     "OTA-writable window exceeds the flash");
BUILD_ASSERT(SYN_PART_REGISTRY_A_SIZE == SYN_PART_REGISTRY_B_SIZE,
	     "registry copies must be the same size");
BUILD_ASSERT(SYN_PART_SLOT_A_SIZE == SYN_PART_SLOT_B_SIZE,
	     "model slots must be the same size");

/* Cross-check against the device tree partition nodes when the
 * synaptic_partitions.overlay is applied to the build.
 */
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_cpu0_fw))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_cpu0_fw)) == SYN_PART_CPU0_FW_OFFSET,
	     "DT syn_part_cpu0_fw offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_cpu0_fw)) == SYN_PART_CPU0_FW_SIZE,
	     "DT syn_part_cpu0_fw size diverged from syn_flash_map.h");
#endif
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_cpu1_img))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_cpu1_img)) == SYN_PART_CPU1_IMG_OFFSET,
	     "DT syn_part_cpu1_img offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_cpu1_img)) == SYN_PART_CPU1_IMG_SIZE,
	     "DT syn_part_cpu1_img size diverged from syn_flash_map.h");
#endif
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_registry_a))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_registry_a)) == SYN_PART_REGISTRY_A_OFFSET,
	     "DT syn_part_registry_a offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_registry_a)) == SYN_PART_REGISTRY_A_SIZE,
	     "DT syn_part_registry_a size diverged from syn_flash_map.h");
#endif
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_registry_b))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_registry_b)) == SYN_PART_REGISTRY_B_OFFSET,
	     "DT syn_part_registry_b offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_registry_b)) == SYN_PART_REGISTRY_B_SIZE,
	     "DT syn_part_registry_b size diverged from syn_flash_map.h");
#endif
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_slot_a))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_slot_a)) == SYN_PART_SLOT_A_OFFSET,
	     "DT syn_part_slot_a offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_slot_a)) == SYN_PART_SLOT_A_SIZE,
	     "DT syn_part_slot_a size diverged from syn_flash_map.h");
#endif
#if DT_NODE_EXISTS(DT_NODELABEL(syn_part_slot_b))
BUILD_ASSERT(DT_REG_ADDR(DT_NODELABEL(syn_part_slot_b)) == SYN_PART_SLOT_B_OFFSET,
	     "DT syn_part_slot_b offset diverged from syn_flash_map.h");
BUILD_ASSERT(DT_REG_SIZE(DT_NODELABEL(syn_part_slot_b)) == SYN_PART_SLOT_B_SIZE,
	     "DT syn_part_slot_b size diverged from syn_flash_map.h");
#endif

#endif /* SYNAPTIC_SYN_FLASH_MAP_H_ */
