#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
syn_flash_layout.py - SynapticOS flash partition map generator.

Single source of truth for the on-chip flash layout of the
FRDM-MCXN947 dual-core configuration. Emits:

  - src/core/syn_flash_map.h ............ C constants + BUILD_ASSERTs
  - boards/nxp/frdm_mcxn947/synaptic_partitions.overlay
                                          fixed-partitions DT nodes

Why this layout (revised for dual-core coexistence, Phase 4):

  The MCXN947 has 2 MB of internal flash in two 1 MB blocks with an
  8 KB erase sector. CPU0 executes in place from bank 0 (secure alias
  0x10000000 + offset); CPU1 executes in place from bank 1 at
  0x00100000. Erasing flash a core is executing from disturbs that
  core, and releasing CPU1 into erased flash wedges the whole chip
  (erased-flash ECC bus error on the vector fetch), so:

  - bank 0 is never erased at runtime (CPU0 firmware only),
  - all OTA-writable partitions (model registry + A/B model slots)
    live in the bank 1 tail, above a reserved CPU1 image region that
    no erase or write range may ever touch,
  - CPU1 is held in reset while an OTA session writes bank 1.

Layout (plain / non-secure addresses, all 8 KB aligned):

  bank 0: 0x00000000-0x000FFFFF  cpu0-firmware (never runtime-erased)
  bank 1: 0x00100000-0x0011FFFF  cpu1-image    (excluded from OTA)
          0x00120000-0x00121FFF  syn-registry-a
          0x00122000-0x00123FFF  syn-registry-b
          0x00124000-0x00191FFF  syn-model-slot-a
          0x00192000-0x001FFFFF  syn-model-slot-b

Usage:
  python3 tools/syn_flash_layout.py            # regenerate both files
  python3 tools/syn_flash_layout.py --check    # verify files are current
  python3 tools/syn_flash_layout.py --print    # dump the map to stdout

Python 3.10+, stdlib only.
"""

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

FLASH_TOTAL = 0x0020_0000     # 2 MB internal flash
BANK_SIZE = 0x0010_0000       # two 1 MB blocks
SECTOR = 0x2000               # erase unit (FSL_FEATURE_SYSCON_FLASH_SECTOR_SIZE_BYTES)
PAGE = 128                    # ROM API program page (DT write-block-size)
SECURE_ALIAS = 0x1000_0000    # CPU0 XIP alias of plain flash addresses


@dataclass(frozen=True)
class Partition:
    ident: str       # C macro stem / DT node label stem
    label: str       # DT partition label
    offset: int
    size: int
    read_only: bool
    ota_writable: bool


PARTITIONS = (
    Partition("CPU0_FW",    "cpu0-firmware",    0x0000_0000, 0x0010_0000, True,  False),
    Partition("CPU1_IMG",   "cpu1-image",       0x0010_0000, 0x0002_0000, True,  False),
    Partition("REGISTRY_A", "syn-registry-a",   0x0012_0000, 0x0000_2000, False, True),
    Partition("REGISTRY_B", "syn-registry-b",   0x0012_2000, 0x0000_2000, False, True),
    Partition("SLOT_A",     "syn-model-slot-a", 0x0012_4000, 0x0006_E000, False, True),
    Partition("SLOT_B",     "syn-model-slot-b", 0x0019_2000, 0x0006_E000, False, True),
)

HEADER_PATH = REPO_ROOT / "src" / "core" / "syn_flash_map.h"
OVERLAY_PATH = (REPO_ROOT / "boards" / "nxp" / "frdm_mcxn947"
                / "synaptic_partitions.overlay")

GENERATED_NOTE = ("GENERATED by tools/syn_flash_layout.py - do not edit; "
                  "edit the tool and regenerate.")


def validate():
    """Reject any layout that violates the dual-core safety rules."""
    parts = sorted(PARTITIONS, key=lambda p: p.offset)
    cursor = 0
    for p in parts:
        assert p.offset % SECTOR == 0, f"{p.ident}: offset not sector-aligned"
        assert p.size % SECTOR == 0, f"{p.ident}: size not sector-aligned"
        assert p.offset == cursor, (
            f"{p.ident}: gap or overlap at 0x{cursor:08X}")
        cursor = p.offset + p.size
    assert cursor == FLASH_TOTAL, "layout does not cover the full 2 MB"

    by = {p.ident: p for p in parts}
    cpu1 = by["CPU1_IMG"]
    assert cpu1.offset == BANK_SIZE, "CPU1 image must start at bank 1 base"
    for p in parts:
        if p.ota_writable:
            assert p.offset >= cpu1.offset + cpu1.size, (
                f"{p.ident}: OTA-writable partition below the CPU1 "
                f"image reserve - forbidden (chip-wedge hazard)")
            assert not p.read_only, f"{p.ident}: writable but read-only"
    assert by["REGISTRY_A"].size == by["REGISTRY_B"].size, "registry sizes differ"
    assert by["SLOT_A"].size == by["SLOT_B"].size, "model slot sizes differ"


def emit_header() -> str:
    writable = [p for p in PARTITIONS if p.ota_writable]
    writable_base = min(p.offset for p in writable)
    writable_end = max(p.offset + p.size for p in writable)

    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/*",
        f" * {GENERATED_NOTE}",
        " *",
        " * SynapticOS on-chip flash partition map (FRDM-MCXN947, dual-core).",
        " * All addresses are plain (non-secure); CPU0 memory-mapped reads",
        " * must go through the secure alias (SYN_FLASH_XIP_ADDR).",
        " *",
        " * Safety invariants enforced below:",
        " *  - bank 0 (CPU0 XIP) contains no OTA-writable partition",
        " *  - nothing OTA-writable intersects the CPU1 image reserve",
        " *  - every boundary is aligned to the 8 KB erase sector",
        " */",
        "#ifndef SYNAPTIC_SYN_FLASH_MAP_H_",
        "#define SYNAPTIC_SYN_FLASH_MAP_H_",
        "",
        "#include <zephyr/toolchain.h>",
        "#include <zephyr/devicetree.h>",
        "",
        f"#define SYN_FLASH_TOTAL_SIZE   0x{FLASH_TOTAL:08X}UL",
        f"#define SYN_FLASH_BANK_SIZE    0x{BANK_SIZE:08X}UL",
        f"#define SYN_FLASH_BANK1_BASE   0x{BANK_SIZE:08X}UL",
        f"#define SYN_FLASH_SECTOR_SIZE  0x{SECTOR:04X}UL",
        f"#define SYN_FLASH_PAGE_SIZE    {PAGE}UL",
        f"#define SYN_FLASH_SECURE_ALIAS 0x{SECURE_ALIAS:08X}UL",
        "",
        "/* CPU0 (secure) sees flash at the alias; CPU1 at plain addresses. */",
        "#ifdef CONFIG_SOC_MCXN947_CPU1",
        "#define SYN_FLASH_XIP_ADDR(off) ((uintptr_t)(off))",
        "#else",
        "#define SYN_FLASH_XIP_ADDR(off) ((uintptr_t)(SYN_FLASH_SECURE_ALIAS + (off)))",
        "#endif",
        "",
    ]
    for p in PARTITIONS:
        lines.append(f"#define SYN_PART_{p.ident}_OFFSET 0x{p.offset:08X}UL")
        lines.append(f"#define SYN_PART_{p.ident}_SIZE   0x{p.size:08X}UL")
    lines += [
        "",
        "/* OTA-writable window: nothing outside it may ever be erased or",
        " * programmed at runtime. The flash port layer enforces this at",
        " * runtime as well (last line of defence).",
        " */",
        f"#define SYN_FLASH_WRITABLE_BASE 0x{writable_base:08X}UL",
        f"#define SYN_FLASH_WRITABLE_END  0x{writable_end:08X}UL",
        "",
        "/* Layout invariants (compile-time) */",
    ]

    def ba(cond, msg):
        lines.append(f'BUILD_ASSERT({cond},\n\t     "{msg}");')

    cursor = 0
    for p in PARTITIONS:
        ba(f"SYN_PART_{p.ident}_OFFSET % SYN_FLASH_SECTOR_SIZE == 0UL",
           f"{p.ident} offset not sector-aligned")
        ba(f"SYN_PART_{p.ident}_SIZE % SYN_FLASH_SECTOR_SIZE == 0UL",
           f"{p.ident} size not sector-aligned")
        ba(f"SYN_PART_{p.ident}_OFFSET == 0x{cursor:08X}UL",
           f"{p.ident} not contiguous with previous partition")
        cursor += p.size
    ba("SYN_PART_SLOT_B_OFFSET + SYN_PART_SLOT_B_SIZE == SYN_FLASH_TOTAL_SIZE",
       "map does not cover the full flash")
    ba("SYN_PART_CPU1_IMG_OFFSET == SYN_FLASH_BANK1_BASE",
       "CPU1 image must sit at bank 1 base (SYSCON CPBOOT target)")
    ba("SYN_FLASH_WRITABLE_BASE >= "
       "SYN_PART_CPU1_IMG_OFFSET + SYN_PART_CPU1_IMG_SIZE",
       "OTA-writable window intersects the CPU1 image reserve")
    ba("SYN_FLASH_WRITABLE_END <= SYN_FLASH_TOTAL_SIZE",
       "OTA-writable window exceeds the flash")
    ba("SYN_PART_REGISTRY_A_SIZE == SYN_PART_REGISTRY_B_SIZE",
       "registry copies must be the same size")
    ba("SYN_PART_SLOT_A_SIZE == SYN_PART_SLOT_B_SIZE",
       "model slots must be the same size")

    lines += [
        "",
        "/* Cross-check against the device tree partition nodes when the",
        " * synaptic_partitions.overlay is applied to the build.",
        " */",
    ]
    for p in PARTITIONS:
        node = f"syn_part_{p.ident.lower()}"
        lines.append(f"#if DT_NODE_EXISTS(DT_NODELABEL({node}))")
        ba(f"DT_REG_ADDR(DT_NODELABEL({node})) == SYN_PART_{p.ident}_OFFSET",
           f"DT {node} offset diverged from syn_flash_map.h")
        ba(f"DT_REG_SIZE(DT_NODELABEL({node})) == SYN_PART_{p.ident}_SIZE",
           f"DT {node} size diverged from syn_flash_map.h")
        lines.append("#endif")
    lines += [
        "",
        "#endif /* SYNAPTIC_SYN_FLASH_MAP_H_ */",
        "",
    ]
    return "\n".join(lines)


def emit_overlay() -> str:
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/*",
        f" * {GENERATED_NOTE}",
        " *",
        " * SynapticOS flash partitions for frdm_mcxn947/mcxn947/cpu0.",
        " * Replaces the stock MCUboot-oriented partitions: the stock",
        " * slot1_partition (0x00108000, 992 KB) straddles CPU1's XIP bank",
        " * and must not exist in SynapticOS builds. Must match",
        " * src/core/syn_flash_map.h (BUILD_ASSERTed there).",
        " */",
        "",
        "/delete-node/ &boot_partition;",
        "/delete-node/ &slot0_partition;",
        "/delete-node/ &slot1_partition;",
        "",
        "/ {",
        "\tchosen {",
        "\t\tzephyr,code-partition = &syn_part_cpu0_fw;",
        "\t};",
        "};",
        "",
        "&flash {",
        "\tpartitions {",
        "\t\tcompatible = \"fixed-partitions\";",
        "\t\t#address-cells = <1>;",
        "\t\t#size-cells = <1>;",
        "",
    ]
    for p in PARTITIONS:
        node = f"syn_part_{p.ident.lower()}"
        lines.append(f"\t\t{node}: partition@{p.offset:x} {{")
        lines.append(f"\t\t\tlabel = \"{p.label}\";")
        lines.append(f"\t\t\treg = <0x{p.offset:08x} 0x{p.size:08x}>;")
        if p.read_only:
            lines.append("\t\t\tread-only;")
        lines.append("\t\t};")
        if p is not PARTITIONS[-1]:
            lines.append("")
    lines += [
        "\t};",
        "};",
        "",
    ]
    return "\n".join(lines)


def print_map():
    print(f"{'partition':<18}{'start':>12}{'end':>12}{'size':>10}  flags")
    for p in PARTITIONS:
        flags = []
        if p.read_only:
            flags.append("ro")
        if p.ota_writable:
            flags.append("ota")
        print(f"{p.label:<18}0x{p.offset:08X}  0x{p.offset + p.size - 1:08X}"
              f"{p.size // 1024:>8} KB  {','.join(flags)}")


def main():
    ap = argparse.ArgumentParser(
        description="SynapticOS flash partition map generator")
    ap.add_argument("--check", action="store_true",
                    help="verify generated files match the tool (exit 1 on drift)")
    ap.add_argument("--print", action="store_true", dest="print_map",
                    help="print the partition map and exit")
    args = ap.parse_args()

    validate()

    if args.print_map:
        print_map()
        return 0

    outputs = {HEADER_PATH: emit_header(), OVERLAY_PATH: emit_overlay()}

    if args.check:
        stale = [str(p.relative_to(REPO_ROOT)) for p, content in outputs.items()
                 if not p.exists() or p.read_text() != content]
        if stale:
            print(f"stale generated files: {', '.join(stale)} "
                  f"(run tools/syn_flash_layout.py)", file=sys.stderr)
            return 1
        print("flash layout files are current")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
